[theme]
base="light"
primaryColor="#1b263b"
backgroundColor="white"
secondaryBackgroundColor="#f2f2f2"
textColor="#000000"
showWidgetBorder=true


[theme.sidebar]
backgroundColor="#1b263b"
textColor="white"
secondaryBackgroundColor="black"
showWidgetBorder=true
borderColor="white"